# Generated by Django 5.0.3 on 2024-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=80)),
                ('dt_nasc', models.CharField(max_length=80)),
                ('telefone', models.PositiveIntegerField()),
                ('cpf', models.PositiveIntegerField()),
            ],
        ),
    ]
