# Generated by Django 5.0.3 on 2024-03-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_alunos_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='sexo',
            field=models.CharField(default='Masculino', max_length=20),
        ),
    ]
