# Generated by Django 5.0.3 on 2024-03-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_remove_alunos_foto_alter_alunos_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='sexo',
            field=models.CharField(max_length=1),
        ),
    ]
